# Schema for the configuration files of the fronkit theme.
fronkit.settings:
  type: theme_settings
  label: 'fronkit settings'
  mapping:
    font_size:
      type: integer
      label: Font size
    banner_background:
      type: string
      label: Banner background
